// PLAN.md §0.10: the demo's agents are not language models, and the dashboard says so. The harness records the
// model of every transaction it starts under one of these names; anything else is taken to be real.
export type Simulation = "scripted" | "stub" | "synthetic";

// harness/lib/tasks.mjs (scripted-v1 and the sloppy pair), harness/agents/claude.mjs (the stub) and
// harness/bench/policies.mjs (the bench's agents).
const SIMULATED: ReadonlyMap<string, Simulation> = new Map([
  ["scripted-v1", "scripted"],
  ["sloppy-v0", "scripted"],
  ["claude-stub", "stub"],
  ["synthetic-v1", "synthetic"],
]);

export function simulationOf(model: string | null | undefined): Simulation | null {
  return (model && SIMULATED.get(model)) || null;
}

export function modelLabel(model: string): string {
  const kind = simulationOf(model);
  return kind ? `${model} (${kind})` : model;
}

const WHAT: Record<Simulation, string> = {
  scripted: "Scripted agents replay patches prepared by the demo harness; they are not language models.",
  stub: "Stub agents replay a recorded Claude Code session and apply the task's prepared patch; no model is called.",
  synthetic: "Synthetic agents are generated by the bench: real git, merges and tests, but no real decisions.",
};
const ORDER: Simulation[] = ["scripted", "stub", "synthetic"];

// What the Sidings header says about the agents whose transactions are on the line. Transactions without a
// model say nothing either way; a real model next to simulated ones is named so the tag is not read as "all".
export function simulationTag(models: Iterable<string | null>): { text: string; title: string } | null {
  const kinds = new Set<Simulation>();
  let real = false;
  for (const m of models) {
    if (!m) continue;
    const kind = simulationOf(m);
    if (kind) kinds.add(kind);
    else real = true;
  }
  const present = ORDER.filter((k) => kinds.has(k));
  if (present.length === 0) return null;
  return { text: `${present.join(" + ")}${real ? " + real" : ""} agents`, title: present.map((k) => WHAT[k]).join(" ") };
}
